// =============================================================================
// [Frozen] usage patterns with AutoFixture.AutoNSubstitute
// =============================================================================

using AutoFixture;
using AutoFixture.AutoNSubstitute;
using AutoFixture.Xunit2;
using AwesomeAssertions;
using NSubstitute;
using NSubstitute.ExceptionExtensions;
using Xunit;

namespace MyProject.Tests.FrozenPatterns;

#region Basic Frozen pattern

public class BasicFrozenPatternTests
{
    /// <summary>
    /// [Frozen] guarantees the SUT and the test see the same substitute.
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task BasicFrozenPattern(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        var orderId = 1;
        var expectedOrder = new Order { Id = orderId, Status = "Active" };

        repository.GetByIdAsync(orderId).Returns(expectedOrder);

        var result = await sut.GetOrderAsync(orderId);

        result.Should().BeEquivalentTo(expectedOrder);
        await repository.Received(1).GetByIdAsync(orderId);
    }

    /// <summary>
    /// Correct order: [Frozen] parameters come before the SUT.
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task CorrectParameterOrder(
        [Frozen] IOrderRepository repository,
        [Frozen] INotificationService notifier,
        [Frozen] ILogger<OrderService> logger,
        OrderService sut)
    {
        repository.GetByIdAsync(Arg.Any<int>()).Returns(new Order { Id = 1 });
        notifier.SendAsync(Arg.Any<string>()).Returns(true);

        var result = await sut.GetOrderAsync(1);

        result.Should().NotBeNull();
    }
}

#endregion

#region Multiple frozen dependencies

public class MultipleFrozenDependenciesTests
{
    [Theory]
    [AutoNSubstituteData]
    public async Task FreezeMultipleDependencies(
        [Frozen] IOrderRepository orderRepository,
        [Frozen] ICustomerRepository customerRepository,
        [Frozen] IInventoryService inventoryService,
        OrderProcessingService sut)
    {
        var order = new Order { Id = 1, CustomerId = 100, ProductId = 200 };
        var customer = new Customer { Id = 100, Name = "Test Customer" };

        orderRepository.GetByIdAsync(1).Returns(order);
        customerRepository.GetByIdAsync(100).Returns(customer);
        inventoryService.CheckAvailabilityAsync(200).Returns(true);

        var result = await sut.ProcessOrderAsync(1);

        result.Should().NotBeNull();
        result.CustomerName.Should().Be("Test Customer");
    }
}

#endregion

#region Frozen + auto-generated data

public class FrozenWithAutoGeneratedDataTests
{
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithAutoGeneratedModel(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)
    {
        repository.GetByIdAsync(order.Id).Returns(order);

        var result = await sut.GetOrderAsync(order.Id);

        result.Should().NotBeNull();
        result.Id.Should().Be(order.Id);
    }

    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithAutoGeneratedCollection(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        List<Order> orders)
    {
        repository.GetAllAsync().Returns(orders);

        var result = await sut.GetAllOrdersAsync();

        result.Should().HaveCount(3);
    }
}

#endregion

#region Frozen + IFixture

public class FrozenWithIFixtureTests
{
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithIFixtureControl(
        IFixture fixture,
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        var order = fixture.Build<Order>()
            .With(o => o.Id, 999)
            .With(o => o.Status, "Pending")
            .With(o => o.TotalAmount, 1500.00m)
            .Create();

        repository.GetByIdAsync(999).Returns(order);

        var result = await sut.GetOrderAsync(999);

        result.Should().NotBeNull();
        result.Id.Should().Be(999);
        result.Status.Should().Be("Pending");
        result.TotalAmount.Should().Be(1500.00m);
    }
}

#endregion

#region Verification patterns

public class FrozenVerificationPatternsTests
{
    [Theory]
    [AutoNSubstituteData]
    public async Task VerifyMethodCalled(
        [Frozen] INotificationService notifier,
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)
    {
        repository.GetByIdAsync(order.Id).Returns(order);
        notifier.SendAsync(Arg.Any<string>()).Returns(true);

        await sut.ProcessAndNotifyAsync(order.Id);

        await notifier.Received(1).SendAsync(Arg.Any<string>());
    }

    [Theory]
    [AutoNSubstituteData]
    public async Task VerifyMethodNotCalled(
        [Frozen] INotificationService notifier,
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        repository.GetByIdAsync(Arg.Any<int>()).Returns((Order?)null);

        await sut.ProcessAndNotifyAsync(999);

        // When order is missing, no notification should fire.
        await notifier.DidNotReceive().SendAsync(Arg.Any<string>());
    }

    [Theory]
    [AutoNSubstituteData]
    public async Task VerifyArgumentPassed(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)
    {
        repository.SaveAsync(Arg.Any<Order>()).Returns(true);

        await sut.UpdateOrderStatusAsync(order, "Completed");

        await repository.Received(1).SaveAsync(Arg.Is<Order>(o =>
            o.Id == order.Id &&
            o.Status == "Completed"));
    }
}

#endregion

#region Advanced Frozen patterns

public class AdvancedFrozenPatternsTests
{
    [Theory]
    [AutoNSubstituteData]
    public async Task DifferentReturnsForDifferentInputs(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        var activeOrder = new Order { Id = 1, Status = "Active" };
        var completedOrder = new Order { Id = 2, Status = "Completed" };

        repository.GetByIdAsync(1).Returns(activeOrder);
        repository.GetByIdAsync(2).Returns(completedOrder);

        var result1 = await sut.GetOrderAsync(1);
        var result2 = await sut.GetOrderAsync(2);

        result1.Status.Should().Be("Active");
        result2.Status.Should().Be("Completed");
    }

    [Theory]
    [AutoNSubstituteData]
    public async Task SequentialReturns(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        var orders = new[]
        {
            new Order { Id = 1, Status = "Pending" },
            new Order { Id = 2, Status = "Processing" },
            new Order { Id = 3, Status = "Completed" }
        };

        repository.GetNextOrderAsync()
            .Returns(orders[0], orders[1], orders[2]);

        var result1 = await sut.GetNextOrderAsync();
        var result2 = await sut.GetNextOrderAsync();
        var result3 = await sut.GetNextOrderAsync();

        result1.Status.Should().Be("Pending");
        result2.Status.Should().Be("Processing");
        result3.Status.Should().Be("Completed");
    }

    [Theory]
    [AutoNSubstituteData]
    public async Task SimulateException(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        repository.GetByIdAsync(Arg.Any<int>())
            .ThrowsAsync(new InvalidOperationException("Database connection failed"));

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => sut.GetOrderAsync(1));

        exception.Message.Should().Contain("Database connection failed");
    }
}

#endregion

#region Sample interfaces and classes

public interface IOrderRepository
{
    Task<Order?> GetByIdAsync(int id);
    Task<IEnumerable<Order>> GetAllAsync();
    Task<IEnumerable<Order>> GetByCustomerIdAsync(int customerId);
    Task<Order?> GetNextOrderAsync();
    Task<bool> SaveAsync(Order order);
}

public interface ICustomerRepository
{
    Task<Customer?> GetByIdAsync(int id);
}

public interface INotificationService
{
    Task<bool> SendAsync(string message);
}

public interface IInventoryService
{
    Task<bool> CheckAvailabilityAsync(int productId);
}

public interface ILogger<T>
{
    void LogInformation(string message);
    void LogError(Exception ex, string message);
}

public class Order
{
    public int Id { get; set; }
    public int CustomerId { get; set; }
    public int ProductId { get; set; }
    public string Status { get; set; } = string.Empty;
    public decimal TotalAmount { get; set; }
}

public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class OrderResult
{
    public int OrderId { get; set; }
    public string CustomerName { get; set; } = string.Empty;
}

public class OrderService
{
    private readonly IOrderRepository _repository;
    private readonly INotificationService? _notifier;

    public OrderService(
        IOrderRepository repository,
        INotificationService? notifier = null)
    {
        _repository = repository;
        _notifier = notifier;
    }

    public Task<Order?> GetOrderAsync(int id) => _repository.GetByIdAsync(id);

    public Task<IEnumerable<Order>> GetAllOrdersAsync() => _repository.GetAllAsync();

    public Task<Order?> GetNextOrderAsync() => _repository.GetNextOrderAsync();

    public async Task ProcessAndNotifyAsync(int orderId)
    {
        var order = await _repository.GetByIdAsync(orderId);
        if (order != null && _notifier != null)
        {
            await _notifier.SendAsync($"Order {orderId} processed");
        }
    }

    public async Task UpdateOrderStatusAsync(Order order, string status)
    {
        order.Status = status;
        await _repository.SaveAsync(order);
    }
}

public class OrderProcessingService
{
    private readonly IOrderRepository _orderRepository;
    private readonly ICustomerRepository _customerRepository;
    private readonly IInventoryService _inventoryService;

    public OrderProcessingService(
        IOrderRepository orderRepository,
        ICustomerRepository customerRepository,
        IInventoryService inventoryService)
    {
        _orderRepository = orderRepository;
        _customerRepository = customerRepository;
        _inventoryService = inventoryService;
    }

    public async Task<OrderResult?> ProcessOrderAsync(int orderId)
    {
        var order = await _orderRepository.GetByIdAsync(orderId);
        if (order == null) return null;

        var customer = await _customerRepository.GetByIdAsync(order.CustomerId);
        if (customer == null) return null;

        var available = await _inventoryService.CheckAvailabilityAsync(order.ProductId);
        if (!available) return null;

        return new OrderResult
        {
            OrderId = order.Id,
            CustomerName = customer.Name
        };
    }
}

public class AutoNSubstituteDataAttribute : AutoDataAttribute
{
    public AutoNSubstituteDataAttribute() : base(() =>
        new Fixture().Customize(new AutoNSubstituteCustomization()))
    {
    }
}

#endregion
