using AwesomeAssertions;
using AwesomeAssertions.Primitives;
using System.Linq.Expressions;

namespace YourProject.Tests.CustomAssertions;

/// <summary>
/// Custom assertion extension templates for domain-specific tests.
/// Improves test readability and removes repetition.
/// </summary>

#region Domain-specific assertions — e-commerce sample

/// <summary>
/// Custom assertions for an e-commerce domain.
/// </summary>
public static class ECommerceAssertions
{
    /// <summary>
    /// Verifies that the subject is a valid <see cref="Product"/>.
    /// </summary>
    public static AndConstraint<ObjectAssertions> BeValidProduct(
        this ObjectAssertions assertions,
        string because = "",
        params object[] becauseArgs)
    {
        var product = assertions.Subject as Product;

        product.Should().NotBeNull("Expected a Product object, but found {0}", assertions.Subject?.GetType());

        product!.Id.Should().BeGreaterThan(0, "Product ID must be greater than 0");
        product.Name.Should().NotBeNullOrEmpty("Product name cannot be null or empty");
        product.Price.Should().BeGreaterThan(0, "Product price must be greater than 0");

        return new AndConstraint<ObjectAssertions>(assertions);
    }

    /// <summary>
    /// Verifies that the subject is a valid <see cref="Order"/>.
    /// </summary>
    public static AndConstraint<ObjectAssertions> BeValidOrder(
        this ObjectAssertions assertions,
        string because = "",
        params object[] becauseArgs)
    {
        var order = assertions.Subject as Order;

        order.Should().NotBeNull("Expected an Order object");

        order!.Id.Should().BeGreaterThan(0, "Order ID must be greater than 0");
        order.Items.Should().NotBeNullOrEmpty("Order must contain at least one item");
        order.TotalAmount.Should().BeGreaterThan(0, "Order total amount must be greater than 0");
        order.Items.Should().AllSatisfy(item =>
        {
            item.Quantity.Should().BeGreaterThan(0, "Item quantity must be positive");
            item.Price.Should().BeGreaterThan(0, "Item price must be positive");
        });

        return new AndConstraint<ObjectAssertions>(assertions);
    }

    /// <summary>
    /// Verifies shopping-cart invariants.
    /// </summary>
    public static AndConstraint<ObjectAssertions> BeValidCart(
        this ObjectAssertions assertions)
    {
        var cart = assertions.Subject as ShoppingCart;

        cart.Should().NotBeNull();
        cart!.Items.Should().NotBeNull("Cart items should not be null");
        cart.TotalItems.Should().Be(cart.Items.Count, "Total items count should match actual items");
        cart.TotalAmount.Should().Be(
            cart.Items.Sum(i => i.Price * i.Quantity),
            "Total amount should equal sum of all items");

        return new AndConstraint<ObjectAssertions>(assertions);
    }
}

#endregion

#region Smart exclusion extensions

/// <summary>
/// Reusable exclusion extensions for <see cref="EquivalencyOptions{T}"/>.
/// Automatically skips common auto-generated and audit fields.
/// </summary>
public static class SmartExclusionExtensions
{
    /// <summary>
    /// Excludes auto-generated fields (IDs, timestamps, version numbers).
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAutoGeneratedFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.EndsWith("Id") &&
                              ctx.SelectedMemberInfo.Name.StartsWith("Generated"))
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            .Excluding(ctx => ctx.Path.Contains("Version"))
            .Excluding(ctx => ctx.Path.Contains("RowVersion"))
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// Excludes audit fields (CreatedBy/At, ModifiedBy/At, etc.).
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAuditFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.Contains("CreatedBy"))
            .Excluding(ctx => ctx.Path.Contains("CreatedAt"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedBy"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedAt"))
            .Excluding(ctx => ctx.Path.Contains("LastModified"))
            .Excluding(ctx => ctx.Path.Contains("LastUpdated"));
    }

    /// <summary>
    /// Excludes every <see cref="DateTime"/> / <see cref="DateTimeOffset"/> field.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAllTimeFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.RuntimeType == typeof(DateTime))
            .Excluding(ctx => ctx.RuntimeType == typeof(DateTimeOffset))
            .Excluding(ctx => ctx.RuntimeType == typeof(DateTime?))
            .Excluding(ctx => ctx.RuntimeType == typeof(DateTimeOffset?));
    }

    /// <summary>
    /// Composition: excludes both auto-generated and audit fields.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingCommonAutoFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .ExcludingAutoGeneratedFields()
            .ExcludingAuditFields();
    }
}

#endregion

#region Performance-optimised assertions

/// <summary>
/// Helpers for assertions over large data sets.
/// </summary>
public static class PerformanceOptimizedAssertions
{
    /// <summary>
    /// Sample-based assertion over a large data set.
    /// Counts must match exactly; equivalence is checked on a random sample.
    /// </summary>
    public static void AssertLargeDataSet<T>(
        IEnumerable<T> actual,
        IEnumerable<T> expected,
        int sampleSize = 1000)
    {
        var actualList = actual.ToList();
        var expectedList = expected.ToList();

        actualList.Should().HaveCount(expectedList.Count);

        var totalCount = actualList.Count;
        var n = Math.Min(sampleSize, totalCount);

        var sampleIndices = Enumerable.Range(0, n)
            .Select(_ => Random.Shared.Next(totalCount))
            .Distinct()
            .ToList();

        foreach (var index in sampleIndices)
        {
            actualList[index].Should().BeEquivalentTo(expectedList[index]);
        }
    }

    /// <summary>
    /// Compares only the key properties listed in <paramref name="keySelectors"/>.
    /// </summary>
    public static void AssertKeyPropertiesOnly<T>(
        T actual,
        T expected,
        params Expression<Func<T, object>>[] keySelectors)
    {
        foreach (var selector in keySelectors)
        {
            var actualValue = selector.Compile()(actual);
            var expectedValue = selector.Compile()(expected);

            actualValue.Should().Be(expectedValue,
                $"Key property {selector} should match");
        }
    }
}

#endregion

#region Conditional assertions

/// <summary>
/// Builder for conditionally executing an assertion block.
/// </summary>
public static class ConditionalAssertions
{
    public static ConditionalAssertion<T> When<T>(this T subject, bool condition) =>
        new(subject, condition);
}

public class ConditionalAssertion<T>
{
    private readonly T _subject;
    private readonly bool _condition;

    public ConditionalAssertion(T subject, bool condition)
    {
        _subject = subject;
        _condition = condition;
    }

    public AndConstraint<ObjectAssertions> Then(Action<T> assertion)
    {
        if (_condition) assertion(_subject);
        return new AndConstraint<ObjectAssertions>(_subject.Should());
    }
}

#endregion

#region Usage examples

public class CustomAssertionsUsageExamples
{
    [Fact]
    public void UseCase_DomainSpecificAssertions()
    {
        var product = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m
        };

        product.Should().BeValidProduct();
    }

    [Fact]
    public void UseCase_SmartExclusion()
    {
        var user = new User
        {
            Id = 1,
            Name = "John",
            Email = "john@example.com",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            RowVersion = new byte[] { 1, 2, 3 }
        };

        var retrieved = new User
        {
            Id = 1,
            Name = "John",
            Email = "john@example.com",
            CreatedAt = DateTime.Now.AddDays(-1),
            UpdatedAt = DateTime.Now.AddHours(-2),
            RowVersion = new byte[] { 4, 5, 6 }
        };

        retrieved.Should().BeEquivalentTo(user, options => options
            .ExcludingCommonAutoFields());
    }

    [Fact]
    public void UseCase_LargeDataSetPerformance()
    {
        var largeDataset = Enumerable.Range(1, 100_000)
            .Select(i => new DataRecord { Id = i, Value = $"Record_{i}" })
            .ToList();

        var processed = largeDataset.Select(r => r).ToList();

        PerformanceOptimizedAssertions.AssertLargeDataSet(
            processed,
            largeDataset,
            sampleSize: 1000);
    }

    [Fact]
    public void UseCase_ConditionalAssertions()
    {
        bool isAdmin = true;
        var user = new User
        {
            Id = 1,
            Name = "Admin",
            Email = "admin@example.com"
        };

        user.When(isAdmin)
            .Then(u => u.Name.Should().StartWith("Admin"));

        user.When(!isAdmin)
            .Then(u => u.Name.Should().NotStartWith("Admin"));
    }
}

#endregion

#region Test model classes

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int Stock { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

public class Order
{
    public int Id { get; set; }
    public string CustomerName { get; set; } = string.Empty;
    public List<OrderItem> Items { get; set; } = new();
    public decimal TotalAmount { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class OrderItem
{
    public int ProductId { get; set; }
    public string ProductName { get; set; } = string.Empty;
    public int Quantity { get; set; }
    public decimal Price { get; set; }
}

public class ShoppingCart
{
    public int Id { get; set; }
    public List<OrderItem> Items { get; set; } = new();
    public int TotalItems => Items.Count;
    public decimal TotalAmount => Items.Sum(i => i.Price * i.Quantity);
}

public class User
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public byte[]? RowVersion { get; set; }
}

public class DataRecord
{
    public int Id { get; set; }
    public string Value { get; set; } = string.Empty;
}

#endregion
