using System;
using System.Linq;
using System.Linq.Expressions;
using AwesomeAssertions;
using Xunit;

namespace DotNetTesting.ComplexObjectComparison.Templates;

/// <summary>
/// Reusable field-exclusion strategies and extensions.
/// Reduces repetition across equivalency-based tests.
/// </summary>
public static class ExclusionStrategies
{
    #region Smart-exclusion extensions

    /// <summary>
    /// Excludes common auto-generated fields:
    /// IDs prefixed with <c>Generated</c>, timestamps, version columns.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAutoGeneratedFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            // <Generated>Id pattern
            .Excluding(ctx => ctx.Path.EndsWith("Id") &&
                              ctx.SelectedMemberInfo.Name.StartsWith("Generated"))
            // any "*At" timestamp
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            // any "*Time" field
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            // optimistic-concurrency version
            .Excluding(ctx => ctx.Path.Contains("Version"))
            // EF rowversion
            .Excluding(ctx => ctx.Path.Contains("RowVersion"))
            // Generic timestamp column
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// Excludes audit fields: CreatedBy/At, ModifiedBy/At, UpdatedBy/At, LastModified.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAuditFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.Contains("CreatedBy"))
            .Excluding(ctx => ctx.Path.Contains("CreatedAt"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedBy"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedAt"))
            .Excluding(ctx => ctx.Path.Contains("UpdatedBy"))
            .Excluding(ctx => ctx.Path.Contains("UpdatedAt"))
            .Excluding(ctx => ctx.Path.Contains("LastModified"));
    }

    /// <summary>
    /// Excludes every datetime-shaped field by path.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAllTimeFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            .Excluding(ctx => ctx.Path.EndsWith("Date"))
            .Excluding(ctx => ctx.Path.Contains("DateTime"))
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// Composition: <see cref="ExcludingAutoGeneratedFields"/> + <see cref="ExcludingAuditFields"/>.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingCommonAutoFields<T>(
        this EquivalencyOptions<T> options) =>
        options.ExcludingAutoGeneratedFields().ExcludingAuditFields();

    /// <summary>
    /// EF-specific exclusion bundle. Skips navigation/proxy properties and audit fields.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingEntityFrameworkFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .ExcludingMissingMembers()
            .Excluding(ctx => ctx.Path.Contains("Navigation"))
            .Excluding(ctx => ctx.Path.Contains("Proxy"))
            .ExcludingAutoGeneratedFields()
            .ExcludingAuditFields();
    }

    #endregion

    #region Performance helpers

    /// <summary>
    /// Compares only the supplied key properties — avoids a full graph walk.
    /// </summary>
    public static void AssertKeyPropertiesOnly<T>(
        T actual,
        T expected,
        params Expression<Func<T, object>>[] keySelectors)
    {
        if (keySelectors == null || keySelectors.Length == 0)
        {
            throw new ArgumentException(
                "At least one key property must be supplied.",
                nameof(keySelectors));
        }

        foreach (var selector in keySelectors)
        {
            var actualValue = selector.Compile()(actual);
            var expectedValue = selector.Compile()(expected);

            actualValue.Should().Be(expectedValue,
                $"key property {GetPropertyName(selector)} should match");
        }
    }

    /// <summary>
    /// Extracts the member name from an expression like <c>x =&gt; x.Foo</c>.
    /// </summary>
    private static string GetPropertyName<T>(Expression<Func<T, object>> expression) =>
        expression.Body switch
        {
            MemberExpression memberExpression => memberExpression.Member.Name,
            UnaryExpression { Operand: MemberExpression unaryMember } => unaryMember.Member.Name,
            _ => expression.ToString()
        };

    #endregion

    #region Conditional exclusion

    /// <summary>
    /// Excludes <paramref name="propertySelector"/> only when <paramref name="condition"/> is true.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingWhen<T>(
        this EquivalencyOptions<T> options,
        Expression<Func<T, object>> propertySelector,
        bool condition) =>
        condition ? options.Excluding(propertySelector) : options;

    /// <summary>
    /// Excludes properties whose runtime value equals the type's default.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingDefaultValues<T>(
        this EquivalencyOptions<T> options)
    {
        return options.Excluding(ctx =>
        {
            var value = ctx.SelectedMemberInfo.GetValue(ctx.Subject);
            if (value == null) return false;

            var type = value.GetType();
            var defaultValue = type.IsValueType ? Activator.CreateInstance(type) : null;

            return Equals(value, defaultValue);
        });
    }

    #endregion
}

#region Usage examples

public class ExclusionStrategiesExamples
{
    #region Test models

    public class UserEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;

        // Auto-generated
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int Version { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        // Audit
        public string CreatedBy { get; set; } = string.Empty;
        public string? ModifiedBy { get; set; }
        public DateTime? LastModifiedAt { get; set; }
    }

    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }

        public DateTime CreatedTime { get; set; }
        public DateTime UpdatedTime { get; set; }
        public DateTime? DeletedAt { get; set; }
    }

    #endregion

    [Fact]
    public void Example1_SmartExclusion_ShouldSimplifyTest()
    {
        var original = new UserEntity
        {
            Id = 1,
            Name = "John Doe",
            Email = "john@example.com",
            CreatedAt = DateTime.Now.AddDays(-1),
            UpdatedAt = DateTime.Now.AddDays(-1),
            Version = 1,
            CreatedBy = "system"
        };

        var updated = UpdateUser(original);

        // One-liner handles every auto-managed field.
        updated.Should().BeEquivalentTo(original, options =>
            options.ExcludingCommonAutoFields());
    }

    [Fact]
    public void Example2_CombinedStrategies()
    {
        var product = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m,
            StockQuantity = 10
        };

        var retrieved = GetProductFromDatabase(product.Id);

        retrieved.Should().BeEquivalentTo(product, options =>
            options.ExcludingAllTimeFields()
                   .ExcludingWhen(p => p.StockQuantity,
                       condition: IsStockVolatile()));
    }

    [Fact]
    public void Example3_EntityFrameworkExclusion()
    {
        var expected = new UserEntity
        {
            Id = 1,
            Name = "John Doe",
            Email = "john@example.com"
        };

        var actual = GetUserFromEFContext(1);

        actual.Should().BeEquivalentTo(expected, options =>
            options.ExcludingEntityFrameworkFields());
    }

    [Fact]
    public void Example4_KeyPropertyComparison()
    {
        var expected = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m,
            StockQuantity = 10,
            CreatedTime = DateTime.Now,
            UpdatedTime = DateTime.Now
        };

        var actual = GetProduct(1);

        ExclusionStrategies.AssertKeyPropertiesOnly(
            actual,
            expected,
            p => p.Id,
            p => p.Name,
            p => p.Price,
            p => p.StockQuantity);
    }

    [Fact]
    public void Example5_ConditionalExclusion()
    {
        var product = new Product { Id = 1, Name = "Laptop", Price = 999 };
        var isIntegrationTest = IsRunningInIntegrationTestEnvironment();

        var actual = GetProduct(1);

        actual.Should().BeEquivalentTo(product, options =>
            options.ExcludingAllTimeFields()
                   .ExcludingWhen(p => p.StockQuantity,
                       condition: isIntegrationTest));
    }

    [Fact]
    public void Example6_ExcludingDefaults()
    {
        var partialEntity = new UserEntity
        {
            Name = "John Doe",
            Email = "john@example.com"
            // Id, Version remain default.
        };

        var actual = CreateUser(partialEntity);

        actual.Should().BeEquivalentTo(partialEntity, options =>
            options.ExcludingDefaultValues()
                   .ExcludingCommonAutoFields());
    }

    #region Helpers

    private UserEntity UpdateUser(UserEntity user)
    {
        user.UpdatedAt = DateTime.Now;
        user.Version++;
        user.ModifiedBy = "admin";
        return user;
    }

    private Product GetProductFromDatabase(int id) => new()
    {
        Id = id,
        Name = "Laptop",
        Price = 999.99m,
        StockQuantity = 10,
        CreatedTime = DateTime.Now,
        UpdatedTime = DateTime.Now
    };

    private UserEntity GetUserFromEFContext(int id) => new()
    {
        Id = id,
        Name = "John Doe",
        Email = "john@example.com",
        CreatedAt = DateTime.Now,
        UpdatedAt = DateTime.Now,
        CreatedBy = "system"
    };

    private Product GetProduct(int id) => GetProductFromDatabase(id);

    private UserEntity CreateUser(UserEntity entity)
    {
        entity.Id = 1;
        entity.Version = 1;
        entity.CreatedAt = DateTime.Now;
        entity.CreatedBy = "system";
        return entity;
    }

    private bool IsStockVolatile() => false;
    private bool IsRunningInIntegrationTestEnvironment() => false;

    #endregion
}

#endregion
